services:
    app:
        image: php:8.3-apache
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        networks:
            - koko_network

    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'koko'
            MYSQL_USER: 'koko'
            MYSQL_PASSWORD: '123'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - koko_network

networks:
    koko_network:
        driver: bridge